export const WebNetwork = {
  AB: {
    title: "Awesome Books",
    description: "A curated collection of the best books out there",
    links: ["CD", "EF", "GH"],
    primaryTopic: "reference",
    secondaryTopics: ["art", "science"],
    trust: 1,
  },
  CD: {
    title: "Cool Designs",
    description: "A showcase of the most creative design projects",
    links: ["AB", "EF", "IJ", "MN", "UV"],
    primaryTopic: "art",
    secondaryTopics: ["computers", "recreation"],
    trust: 1,
  },
  EF: {
    title: "Expert Finance",
    description: "The latest financial news and advice from the experts",
    links: ["AB", "CD", "KL"],
    primaryTopic: "business",
    secondaryTopics: ["science", "world"],
    trust: 1,
  },
  GH: {
    title: "Great Health",
    description: "Your guide to a healthy lifestyle",
    links: [],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  IJ: {
    title: "Incredible Jobs",
    description: "Find your dream job with our job search engine",
    links: ["CD", "GH"],
    primaryTopic: "business",
    secondaryTopics: ["computers", "world"],
    trust: 1,
  },
  KL: {
    title: "Killer Lifestyle",
    description: "Get inspired to live your best life",
    links: ["EF", "MN", "OP"],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  MN: {
    title: "My News",
    description: "Stay up-to-date with the latest news and headlines",
    links: ["GH", "IJ"],
    primaryTopic: "news",
    secondaryTopics: ["business", "world"],
    trust: 1,
  },
  OP: {
    title: "Outstanding Photography",
    description: "A gallery of stunning photographs from around the world",
    links: ["KL", "QR"],
    primaryTopic: "art",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  QR: {
    title: "Quick Recipes",
    description:
      "Cook up a storm with our collection of easy and delicious recipes",
    links: ["OP", "ST", "UV"],
    primaryTopic: "home",
    secondaryTopics: ["health", "recreation"],
    trust: 1,
  },
  ST: {
    title: "Super Travel",
    description: "Discover new destinations and plan your next adventure",
    links: ["UV"],
    primaryTopic: "recreation",
    secondaryTopics: ["world", "society"],
    trust: 1,
  },
  UV: {
    title: "Ultimate Video Games",
    description: "The latest news and reviews on video games",
    links: ["QR", "XY", "UV"],
    primaryTopic: "games",
    secondaryTopics: ["computers", "recreation"],
    trust: 0,
  },
  XY: {
    title: "Xtreme Sports",
    description: "The ultimate source for extreme sports enthusiasts",
    links: ["UV", "YZ", "BC"],
    primaryTopic: "sports",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  YZ: {
    title: "Youth Zone",
    description: "The best resources and advice for kids and teens",
    links: ["UV"],
    primaryTopic: "kids and teens",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  DE: {
    title: "Digital Entrepreneur",
    description: "Tips and advice for aspiring digital entrepreneurs",
    links: ["AB", "GH"],
    primaryTopic: "business",
    secondaryTopics: ["computers", "society"],
    trust: 1,
  },
  FG: {
    title: "Fashionista",
    description: "All things fashion and style",
    links: ["IJ", "KL"],
    primaryTopic: "recreation",
    secondaryTopics: ["society"],
    trust: 1,
  },
  HI: {
    title: "Home Decor",
    description: "Inspiration for decorating your home",
    links: ["AB", "QR"],
    primaryTopic: "home",
    secondaryTopics: ["recreation"],
    trust: 1,
  },
  JK: {
    title: "Job Search",
    description: "Find the perfect job for you",
    links: ["MN", "OP", "XY"],
    primaryTopic: "business",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  LM: {
    title: "Lifelong Learning",
    description: "Never stop learning with our online courses and resources",
    links: ["FG", "ST"],
    primaryTopic: "education",
    secondaryTopics: ["reference", "computers"],
    trust: 1,
  },
  NO: {
    title: "Nature",
    description: "Explore and appreciate the beauty of nature",
    links: ["YZ", "XY"],
    primaryTopic: "recreation",
    secondaryTopics: ["science"],
    trust: 1,
  },
  PQ: {
    title: "Pet Lovers",
    description: "For those who love and care for their pets",
    links: [],
    primaryTopic: "recreation",
    secondaryTopics: ["society"],
    trust: 1,
  },
  RS: {
    title: "Real Estate",
    description: "Find your dream home or investment property",
    links: ["HI"],
    primaryTopic: "business",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  TU: {
    title: "Technology News",
    description: "Stay up-to-date with the latest in tech",
    links: ["BC", "UV"],
    primaryTopic: "computers",
    secondaryTopics: ["science"],
    trust: 1,
  },
  BC: {
    title: "Best Cars",
    description: "The latest news and reviews on cars",
    links: ["TU", "XY"],
    primaryTopic: "recreation",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  WX: {
    title: "World Explorer",
    description: "Travel the world and discover new cultures and destinations",
    links: ["NO", "ST", "PQ"],
    primaryTopic: "recreation",
    secondaryTopics: ["regional", "world"],
    trust: 1,
  },
  YX: {
    title: "Yoga & Fitness",
    description: "Improve your wellbeing with yoga and fitness exercises",
    links: ["FG", "GH", "KL"],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "sports"],
    trust: 1,
  },
  ZA: {
    title: "Zero Waste Living",
    description: "Learn how to reduce waste and live a more sustainable life",
    links: ["HI", "QR"],
    primaryTopic: "home",
    secondaryTopics: ["recreation", "science"],
    trust: 1,
  },
  VB: {
    title: "Virtual Reality News",
    description: "The latest news and developments in virtual reality",
    links: ["TU", "UV", "WX"],
    primaryTopic: "computers",
    secondaryTopics: ["games", "recreation"],
    trust: 1,
  },
  WZ: {
    title: "Women in Tech",
    description: "Empowering women in the technology industry",
    links: ["TU", "JK"],
    primaryTopic: "computers",
    secondaryTopics: ["society", "world"],
    trust: 1,
  },
  AC: {
    title: "Amazing Cooking",
    description: "Explore delicious recipes and cooking techniques",
    links: ["QR", "FG"],
    primaryTopic: "home",
    secondaryTopics: ["recreation", "shopping"],
    trust: 1,
  },
  BD: {
    title: "Blockchain Daily",
    description: "Stay updated with the latest news in blockchain technology",
    links: ["TU", "DE"],
    primaryTopic: "computers",
    secondaryTopics: ["business", "world"],
    trust: 1,
  },
  CE: {
    title: "Creative Education",
    description: "Innovative approaches to learning and teaching",
    links: ["LM", "YZ"],
    primaryTopic: "education",
    secondaryTopics: ["reference", "society"],
    trust: 1,
  },
  DF: {
    title: "Drones & Robotics",
    description: "Discover the world of drones and robotics",
    links: ["TU", "NO"],
    primaryTopic: "science",
    secondaryTopics: ["computers", "recreation"],
    trust: 1,
  },
  EG: {
    title: "Eco Gardening",
    description: "Tips and tricks for sustainable gardening",
    links: ["ZA", "NO"],
    primaryTopic: "home",
    secondaryTopics: ["science", "recreation"],
    trust: 1,
  },
  FH: {
    title: "Film Hub",
    description: "The latest movie news, reviews, and trailers",
    links: ["WZ", "OP"],
    primaryTopic: "recreation",
    secondaryTopics: ["art", "society"],
    trust: 1,
  },
  GI: {
    title: "Gadget Innovations",
    description: "Stay up-to-date with the latest gadget innovations",
    links: ["TU", "VB"],
    primaryTopic: "computers",
    secondaryTopics: ["science", "recreation"],
    trust: 1,
  },
  HJ: {
    title: "Healthy Juices",
    description: "Delicious and nutritious juice recipes for a healthier life",
    links: ["YX", "GH", "QR"],
    primaryTopic: "health",
    secondaryTopics: ["home", "recreation"],
    trust: 1,
  },
  IK: {
    title: "Interior Design",
    description: "Explore the world of interior design and get inspired",
    links: ["HI", "FG"],
    primaryTopic: "home",
    secondaryTopics: ["art", "recreation"],
    trust: 1,
  },
  LO: {
    title: "Language Online",
    description: "Learn a new language with our online courses and resources",
    links: ["CE", "LM"],
    primaryTopic: "education",
    secondaryTopics: ["reference", "world"],
    trust: 1,
  },
  MP: {
    title: "Music Pulse",
    description: "Discover new music, artists, and albums",
    links: ["FH", "WZ"],
    primaryTopic: "recreation",
    secondaryTopics: ["art", "society"],
    trust: 1,
  },
  QW: {
    title: "Quantum World",
    description: "Explore the fascinating world of quantum physics",
    links: ["DF", "GI"],
    primaryTopic: "science",
    secondaryTopics: ["computers", "education"],
    trust: 1,
  },
  RT: {
    title: "Running Tips",
    description: "Improve your running performance and avoid injuries",
    links: ["YX", "XY"],
    primaryTopic: "sports",
    secondaryTopics: ["health", "recreation"],
    trust: 1,
  },
  SZ: {
    title: "Solar Zone",
    description: "Learn about solar energy and its applications",
    links: ["EG", "QW"],
    primaryTopic: "science",
    secondaryTopics: ["home", "world"],
    trust: 1,
  },
  TA: {
    title: "Tech Advances",
    description: "Stay informed about the latest advances in technology",
    links: ["GI", "TU", "VB"],
    primaryTopic: "computers",
    secondaryTopics: ["science", "recreation"],
    trust: 1,
  },
  UQ: {
    title: "Urban Quest",
    description: "Discover hidden gems in cities around the world",
    links: ["ST", "WX"],
    primaryTopic: "recreation",
    secondaryTopics: ["regional", "world"],
    trust: 1,
  },
  VN: {
    title: "Vegan Nutrition",
    description: "Learn about vegan nutrition and diet for a healthier life",
    links: ["GH", "HJ"],
    primaryTopic: "health",
    secondaryTopics: ["home", "recreation"],
    trust: 1,
  },
  ZB: {
    title: "Zoology & Biodiversity",
    description: "Explore the amazing world of animals and their habitats",
    links: ["NO", "SZ"],
    primaryTopic: "science",
    secondaryTopics: ["education", "recreation"],
    trust: 1,
  },
  AJ: {
    title: "Artistic Journey",
    description:
      "Explore various art forms and techniques from around the world",
    links: ["AB", "CD", "ST"],
    primaryTopic: "art",
    secondaryTopics: ["recreation", "world"],
    trust: 1,
  },

  BK: {
    title: "Business Knowledge",
    description:
      "An online resource for entrepreneurs and business professionals",
    links: ["MN", "OP", "EF"],
    primaryTopic: "business",
    secondaryTopics: ["reference", "society"],
    trust: 1,
  },

  CL: {
    title: "Computer Lab",
    description:
      "A hub for computer enthusiasts to learn and share their knowledge",
    links: ["QR", "GH", "IJ"],
    primaryTopic: "computers",
    secondaryTopics: ["science", "education"],
    trust: 1,
  },

  DM: {
    title: "Digital Marketing",
    description:
      "Strategies, tips, and resources for effective digital marketing",
    links: ["KL", "UV", "CD"],
    primaryTopic: "business",
    secondaryTopics: ["computers", "reference"],
    trust: 1,
  },

  EN: {
    title: "Eco News",
    description: "Stay informed about the latest environmental news and issues",
    links: ["XY", "YZ", "ST"],
    primaryTopic: "news",
    secondaryTopics: ["science", "society"],
    trust: 1,
  },

  FO: {
    title: "Fitness Online",
    description: "An online community for fitness enthusiasts and trainers",
    links: ["DE", "FG", "HI"],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "sports"],
    trust: 1,
  },

  GP: {
    title: "Gaming Paradise",
    description: "Discover the latest games, reviews, and gaming news",
    links: ["JK", "LM", "NO"],
    primaryTopic: "games",
    secondaryTopics: ["computers", "recreation"],
    trust: 1,
  },

  HQ: {
    title: "Home Quarters",
    description:
      "Home improvement, design ideas, and DIY projects for homeowners",
    links: ["PQ", "RS", "TU"],
    primaryTopic: "home",
    secondaryTopics: ["shopping", "recreation"],
    trust: 1,
  },

  IR: {
    title: "Innovative Recipes",
    description: "Delicious and creative recipes from around the globe",
    links: ["BC", "WX", "YZ"],
    primaryTopic: "home",
    secondaryTopics: ["recreation", "world"],
    trust: 1,
  },

  JS: {
    title: "Junior Sports",
    description: "A resource for kids and teens to learn about various sports",
    links: ["YX", "ZA", "VB"],
    primaryTopic: "sports",
    secondaryTopics: ["kids and teens", "recreation"],
    trust: 1,
  },

  KT: {
    title: "Kids' Tech",
    description:
      "Exploring technology and learning resources for children and teens",
    links: ["WZ", "AC", "BD"],
    primaryTopic: "kids and teens",
    secondaryTopics: ["computers", "education"],
    trust: 1,
  },

  LU: {
    title: "Language Universe",
    description: "Learn and practice different languages with native speakers",
    links: ["CE", "DF", "EG"],
    primaryTopic: "reference",
    secondaryTopics: ["education", "world"],
    trust: 1,
  },

  MV: {
    title: "Movie Vault",
    description:
      "A comprehensive database of movies, reviews, and industry news",
    links: ["FH", "GI", "HJ"],
    primaryTopic: "recreation",
    secondaryTopics: ["art", "society"],
    trust: 1,
  },

  NW: {
    title: "Nutrition World",
    description: "Explore the world of nutrition, food, and health",
    links: ["IK", "LO", "MP"],
    primaryTopic: "health",
    secondaryTopics: ["science", "home"],
    trust: 1,
  },

  OX: {
    title: "Outdoor Xtreme",
    description: "A guide to outdoor adventure sports and activities",
    links: ["QW", "RT", "SZ"],
    primaryTopic: "sports",
    secondaryTopics: ["recreation", "travel"],
    trust: 1,
  },

  PY: {
    title: "Pet Yard",
    description: "Information on pet care, training, and adoption",
    links: ["TA", "UQ", "VN"],
    primaryTopic: "home",
    secondaryTopics: ["recreation", "shopping"],
    trust: 1,
  },

  QZ: {
    title: "Quantum Zone",
    description:
      "A dive into the world of quantum physics and its applications",
    links: ["ZB", "BC", "CE"],
    primaryTopic: "science",
    secondaryTopics: ["education", "computers"],
    trust: 1,
  },

  RA: {
    title: "Robotics Arena",
    description: "Learn about robotics and their impact on society",
    links: ["DF", "EG", "FH"],
    primaryTopic: "computers",
    secondaryTopics: ["science", "education"],
    trust: 1,
  },

  SB: {
    title: "Sustainable Business",
    description: "Innovative ideas for eco-friendly businesses and practices",
    links: ["GI", "HJ", "IK"],
    primaryTopic: "business",
    secondaryTopics: ["science", "society"],
    trust: 1,
  },

  TC: {
    title: "Traveler's Corner",
    description: "A resource for travelers to discover new destinations",
    links: ["LO", "MP", "QW"],
    primaryTopic: "recreation",
    secondaryTopics: ["world", "shopping"],
    trust: 1,
  },

  UD: {
    title: "Urban Design",
    description: "Exploring innovative urban planning and architecture",
    links: ["RT", "SZ", "TA"],
    primaryTopic: "art",
    secondaryTopics: ["science", "home"],
    trust: 1,
  },

  VE: {
    title: "Virtual Education",
    description: "Discover online learning platforms and educational resources",
    links: ["UQ", "VN", "ZB"],
    primaryTopic: "reference",
    secondaryTopics: ["computers", "kids and teens"],
    trust: 1,
  },

  WF: {
    title: "Wildlife Friends",
    description: "Learn about wildlife conservation and animal behavior",
    links: ["BC", "CE", "DF"],
    primaryTopic: "science",
    secondaryTopics: ["recreation", "world"],
    trust: 1,
  },

  XG: {
    title: "Extreme Games",
    description:
      "A showcase of extreme sports and adrenaline-pumping activities",
    links: ["EG", "FH", "GI"],
    primaryTopic: "sports",
    secondaryTopics: ["recreation", "health"],
    trust: 1,
  },

  YH: {
    title: "Youth Health",
    description: "Health resources and advice specifically for kids and teens",
    links: ["HJ", "IK", "LO"],
    primaryTopic: "health",
    secondaryTopics: ["kids and teens", "science"],
    trust: 1,
  },

  ZI: {
    title: "Zero Impact",
    description:
      "A guide to reducing your carbon footprint and living sustainably",
    links: ["MP", "QW", "RT"],
    primaryTopic: "science",
    secondaryTopics: ["home", "society"],

    trust: 1,
  },

  AT: {
    title: "Art Journal",
    description:
      "A collection of contemporary art, artist interviews, and exhibition news",
    links: ["SZ", "TA", "UQ"],
    primaryTopic: "art",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },

  KC: {
    title: "Kids' Corner",
    description:
      "Fun activities, games, and educational resources for children",
    links: ["VN", "ZB", "BC"],
    primaryTopic: "kids and teens",
    secondaryTopics: ["recreation", "education"],
    trust: 1,
  },

  LD: {
    title: "Language Discovery",
    description: "Language learning tips, resources, and online courses",
    links: ["CE", "DF", "EG"],
    primaryTopic: "reference",
    secondaryTopics: ["education", "world"],
    trust: 1,
  },

  ME: {
    title: "Music Enthusiast",
    description:
      "A hub for music lovers, featuring news, reviews, and artist interviews",
    links: ["FH", "GI", "HJ"],
    primaryTopic: "recreation",
    secondaryTopics: ["art", "society"],
    trust: 1,
  },

  NF: {
    title: "Nature Focus",
    description:
      "Discover the beauty of nature and ways to protect our environment",
    links: ["IK", "LO", "MP"],
    primaryTopic: "science",
    secondaryTopics: ["recreation", "home"],
    trust: 1,
  },

  OG: {
    title: "Online Gaming",
    description:
      "Explore the world of online gaming, from MMORPGs to strategy games",
    links: ["QW", "RT", "SZ"],
    primaryTopic: "games",
    secondaryTopics: ["computers", "recreation"],
    trust: 1,
  },
  VD: {
    title: "Virtual Design Studio",
    description:
      "A platform for digital artists and designers to showcase their work",
    links: ["WZ", "AC"],
    primaryTopic: "art",
    secondaryTopics: ["computers"],
    trust: 1,
  },
  FI: {
    title: "Fitness Insider",
    description: "Your go-to source for all things fitness and health",
    links: ["BD", "CE", "DF"],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  OQ: {
    title: "Online Quiz",
    description: "A fun and educational platform for testing your knowledge",
    links: ["RS", "TU"],
    primaryTopic: "education",
    secondaryTopics: ["recreation"],
    trust: 1,
  },
  BX: {
    title: "Business Xpress",
    description: "A comprehensive resource for business news and information",
    links: ["YZ", "DE", "FG"],
    primaryTopic: "business",
    secondaryTopics: ["news", "reference"],
    trust: 1,
  },
  KM: {
    title: "Kids' Music",
    description: "A site for children's music and entertainment",
    links: ["NO", "PQ"],
    primaryTopic: "kids and teens",
    secondaryTopics: ["recreation"],
    trust: 1,
  },
  JF: {
    title: "Job Finder",
    description:
      "A job search engine that connects job seekers with opportunities",
    links: ["TU", "BC"],
    primaryTopic: "business",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  SG: {
    title: "Science Gurus",
    description:
      "A community of scientists and science enthusiasts sharing knowledge and ideas",
    links: ["WX", "YX"],
    primaryTopic: "science",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  ZN: {
    title: "Zoo News",
    description: "The latest news and events from zoos around the world",
    links: ["ZA", "VB"],
    primaryTopic: "recreation",
    secondaryTopics: ["news"],
    trust: 1,
  },
  AH: {
    title: "Art Haven",
    description: "A platform for artists to connect and share their work",
    links: ["WZ", "AC"],
    primaryTopic: "art",
    secondaryTopics: ["society"],
    trust: 1,
  },
  LB: {
    title: "Local Brews",
    description: "A guide to local craft breweries and their products",
    links: ["ZI", "KC"],
    primaryTopic: "recreation",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  KJ: {
    title: "Kitchen Delight",
    description: "Find delicious and healthy recipes to cook at home",
    links: ["LM", "NO"],
    primaryTopic: "health",
    secondaryTopics: ["food", "home"],
    trust: 1,
  },
  PU: {
    title: "Planet Universe",
    description: "Explore the mysteries of the universe and learn about space",
    links: ["QZ", "RA", "SB"],
    primaryTopic: "science",
    secondaryTopics: ["education", "recreation"],
    trust: 1,
  },
  WC: {
    title: "World Cinema",
    description: "Discover the best movies from around the world",
    links: ["YH", "ZI"],
    primaryTopic: "art",
    secondaryTopics: ["entertainment", "culture"],
    trust: 1,
  },
  QN: {
    title: "Quick News",
    description: "Get the latest news from around the world in a flash",
    links: ["UV"],
    primaryTopic: "news",
    secondaryTopics: ["politics", "business"],
    trust: 1,
  },
  GD: {
    title: "Gaming Den",
    description: "Find the latest gaming news, reviews, and guides",
    links: ["FI", "OQ", "BX"],
    primaryTopic: "games",
    secondaryTopics: ["entertainment", "technology"],
    trust: 1,
  },
  MJ: {
    title: "Music Junction",
    description: "Discover new music and connect with fellow music lovers",
    links: ["SG", "ZN"],
    primaryTopic: "art",
    secondaryTopics: ["culture", "recreation"],
    trust: 1,
  },
  VT: {
    title: "Virtual Travel",
    description: "Explore the world from the comfort of your own home",
    links: ["VD"],
    primaryTopic: "recreation",
    secondaryTopics: ["travel", "culture"],
    trust: 1,
  },
  YD: {
    title: "Your Diet",
    description: "Get personalized nutrition plans and advice from experts",
    links: ["FG"],
    primaryTopic: "health",
    secondaryTopics: ["food", "fitness"],
    trust: 1,
  },
  PI: {
    title: "Pet Information",
    description: "Learn everything you need to know about your furry friends",
    links: ["HJ", "LO"],
    primaryTopic: "home",
    secondaryTopics: ["animals", "recreation"],
    trust: 1,
  },
  TS: {
    title: "Tech Savvy",
    description: "Stay up-to-date with the latest technology news and reviews",
    links: ["MV", "NW", "OX"],
    primaryTopic: "computers",
    secondaryTopics: ["business", "entertainment"],
    trust: 1,
  },
  ZZ: {
    title: "Zoo Zone",
    description: "A community for zookeepers and animal lovers",
    links: ["ZI", "KC"],
    primaryTopic: "recreation",
    secondaryTopics: ["animals", "society"],
    trust: 1,
  },
  KF: {
    title: "Kicks for You",
    description: "The ultimate source for sneakerheads",
    links: [],
    primaryTopic: "shopping",
    secondaryTopics: ["recreation", "sports"],
    trust: 1,
  },
  QA: {
    title: "Quick and Easy Recipes",
    description: "Delicious recipes for any occasion",
    links: ["JF"],
    primaryTopic: "home",
    secondaryTopics: ["health", "recreation"],
    trust: 1,
  },
  UV: {
    title: "Ultimate Vehicles",
    description:
      "All the latest news and reviews on cars, motorcycles, and more",
    links: ["MP"],
    primaryTopic: "recreation",
    secondaryTopics: ["reference", "science"],
    trust: 1,
  },
  WH: {
    title: "World History Hub",
    description:
      "Explore the fascinating events and figures that shaped our world",
    links: ["LD"],
    primaryTopic: "reference",
    secondaryTopics: ["art", "science"],
    trust: 1,
  },
  TV: {
    title: "TechVision",
    description: "Stay up-to-date with the latest technology news and trends",
    links: ["QN"],
    primaryTopic: "computers",
    secondaryTopics: ["science", "recreation"],
    trust: 1,
  },
  ZW: {
    title: "Zen Wellness",
    description:
      "Find balance and peace in your life with our tips and practices",
    links: [],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "reference"],
    trust: 1,
  },
  OP: {
    title: "Outdoor Pursuits",
    description: "Discover new adventures and explore the great outdoors",
    links: ["YD"],
    primaryTopic: "recreation",
    secondaryTopics: ["sports", "reference"],
    trust: 1,
  },
  AI: {
    title: "Art Insider",
    description: "Get an inside look at the world of art and artists",
    links: ["BK"],
    primaryTopic: "art",
    secondaryTopics: ["reference", "society"],
    trust: 1,
  },
  MY: {
    title: "Music Yard",
    description: "Find new tunes and old favorites from all genres of music",
    links: ["PQ"],
    primaryTopic: "recreation",
    secondaryTopics: ["reference", "art"],
    trust: 1,
  },
  XR: {
    title: "Xtreme Racing",
    description: "The ultimate destination for motorsport fans",
    links: ["GI"],
    primaryTopic: "recreation",
    secondaryTopics: ["sports", "reference"],
    trust: 1,
  },
  VA: {
    title: "Virtual Adventures",
    description:
      "Explore the world from your couch with our virtual tours and experiences",
    links: [],
    primaryTopic: "recreation",
    secondaryTopics: ["travel", "technology"],
    trust: 1,
  },
  OJ: {
    title: "Online Journal",
    description: "Write and share your thoughts with the world",
    links: [],
    primaryTopic: "society",
    secondaryTopics: ["writing", "media"],
    trust: 1,
  },
  QM: {
    title: "Quick Meals",
    description: "Get easy and delicious meal ideas for busy people",
    links: [],
    primaryTopic: "food",
    secondaryTopics: ["health", "home"],
    trust: 1,
  },
  UY: {
    title: "Ultimate Yoga",
    description: "Learn and practice yoga with our expert instructors",
    links: [],
    primaryTopic: "health",
    secondaryTopics: ["fitness", "spirituality"],
    trust: 1,
  },
  NX: {
    title: "News X",
    description: "Get the latest news and updates from around the world",
    links: [],
    primaryTopic: "news",
    secondaryTopics: ["politics", "business"],
    trust: 1,
  },
  ZT: {
    title: "Zen Travel",
    description:
      "Discover peace and tranquility with our mindful travel experiences",
    links: [],
    primaryTopic: "travel",
    secondaryTopics: ["health", "spirituality"],
    trust: 1,
  },
  EL: {
    title: "Eco Living",
    description: "Live sustainably with our eco-friendly products and tips",
    links: [],
    primaryTopic: "home",
    secondaryTopics: ["environment", "society"],
    trust: 1,
  },
  WQ: {
    title: "World Quiz",
    description:
      "Test your knowledge with our fun and challenging quizzes about the world",
    links: [],
    primaryTopic: "education",
    secondaryTopics: ["games", "society"],
    trust: 1,
  },
  GZ: {
    title: "Green Zone",
    description:
      "Get tips and advice for living a green and sustainable lifestyle",
    links: [],
    primaryTopic: "environment",
    secondaryTopics: ["home", "health"],
    trust: 1,
  },
  PF: {
    title: "Photo Fun",
    description:
      "Edit and enhance your photos with our fun and easy-to-use tools",
    links: [],
    primaryTopic: "art",
    secondaryTopics: ["technology", "recreation"],
    trust: 1,
  },
};
