export const WebNetwork = {
  AB: {
    title: "Awesome Books",
    description: "A curated collection of the best books out there",
    links: ["CD", "EF", "GH"],
    primaryTopic: "reference",
    secondaryTopics: ["art", "science"],
    trust: 1,
  },
  CD: {
    title: "Cool Designs",
    description: "A showcase of the most creative design projects",
    links: ["AB", "EF", "IJ", "MN", "UV"],
    primaryTopic: "art",
    secondaryTopics: ["computers", "recreation"],
    trust: 1,
  },
  EF: {
    title: "Expert Finance",
    description: "The latest financial news and advice from the experts",
    links: ["AB", "CD", "KL"],
    primaryTopic: "business",
    secondaryTopics: ["science", "world"],
    trust: 1,
  },
  GH: {
    title: "Great Health",
    description: "Your guide to a healthy lifestyle",
    links: [],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  IJ: {
    title: "Incredible Jobs",
    description: "Find your dream job with our job search engine",
    links: ["CD", "GH"],
    primaryTopic: "business",
    secondaryTopics: ["computers", "world"],
    trust: 1,
  },
  KL: {
    title: "Killer Lifestyle",
    description: "Get inspired to live your best life",
    links: ["EF", "MN", "OP"],
    primaryTopic: "health",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  MN: {
    title: "My News",
    description: "Stay up-to-date with the latest news and headlines",
    links: ["GH", "IJ"],
    primaryTopic: "news",
    secondaryTopics: ["business", "world"],
    trust: 1,
  },
  OP: {
    title: "Outstanding Photography",
    description: "A gallery of stunning photographs from around the world",
    links: ["KL", "QR"],
    primaryTopic: "art",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  QR: {
    title: "Quick Recipes",
    description:
      "Cook up a storm with our collection of easy and delicious recipes",
    links: ["OP", "ST", "UV"],
    primaryTopic: "home",
    secondaryTopics: ["health", "recreation"],
    trust: 1,
  },
  ST: {
    title: "Super Travel",
    description: "Discover new destinations and plan your next adventure",
    links: ["UV"],
    primaryTopic: "recreation",
    secondaryTopics: ["world", "society"],
    trust: 1,
  },
  UV: {
    title: "Ultimate Video Games",
    description: "The latest news and reviews on video games",
    links: ["QR", "XY", "UV"],
    primaryTopic: "games",
    secondaryTopics: ["computers", "recreation"],
    trust: 0,
  },
  XY: {
    title: "Xtreme Sports",
    description: "The ultimate source for extreme sports enthusiasts",
    links: ["UV", "YZ", "BC"],
    primaryTopic: "sports",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  YZ: {
    title: "Youth Zone",
    description: "The best resources and advice for kids and teens",
    links: ["UV"],
    primaryTopic: "kids and teens",
    secondaryTopics: ["recreation", "society"],
    trust: 1,
  },
  DE: {
    title: "Digital Entrepreneur",
    description: "Tips and advice for aspiring digital entrepreneurs",
    links: ["AB", "GH"],
    primaryTopic: "business",
    secondaryTopics: ["computers", "society"],
    trust: 1,
  },
  FG: {
    title: "Fashionista",
    description: "All things fashion and style",
    links: ["IJ", "KL"],
    primaryTopic: "recreation",
    secondaryTopics: ["society"],
    trust: 1,
  },
  HI: {
    title: "Home Decor",
    description: "Inspiration for decorating your home",
    links: ["AB", "QR"],
    primaryTopic: "home",
    secondaryTopics: ["recreation"],
    trust: 1,
  },
  JK: {
    title: "Job Search",
    description: "Find the perfect job for you",
    links: ["MN", "OP", "XY"],
    primaryTopic: "business",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  LM: {
    title: "Lifelong Learning",
    description: "Never stop learning with our online courses and resources",
    links: ["FG", "ST"],
    primaryTopic: "education",
    secondaryTopics: ["reference", "computers"],
    trust: 1,
  },
  NO: {
    title: "Nature",
    description: "Explore and appreciate the beauty of nature",
    links: ["YZ", "XY"],
    primaryTopic: "recreation",
    secondaryTopics: ["science"],
    trust: 1,
  },
  PQ: {
    title: "Pet Lovers",
    description: "For those who love and care for their pets",
    links: [],
    primaryTopic: "recreation",
    secondaryTopics: ["society"],
    trust: 1,
  },
  RS: {
    title: "Real Estate",
    description: "Find your dream home or investment property",
    links: ["HI"],
    primaryTopic: "business",
    secondaryTopics: ["reference"],
    trust: 1,
  },
  TU: {
    title: "Technology News",
    description: "Stay up-to-date with the latest in tech",
    links: ["BC", "UV"],
    primaryTopic: "computers",
    secondaryTopics: ["science"],
    trust: 1,
  },
  BC: {
    title: "Best Cars",
    description: "The latest news and reviews on cars",
    links: ["TU", "XY"],
    primaryTopic: "recreation",
    secondaryTopics: ["reference"],
    trust: 1,
  }
};
